global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'locallm_server'
    static_configs:
      - targets: ['locallm_server:8001']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
